anchor/models/post.php

Fixed issue with search system as described in #791 . Queries created
for search function would be like
```
WHERE `anchor_posts`.`status` = ? AND `anchor_posts`.`title` like ? OR
`anchor_posts`.`html` like ?
```
but if both the title and content of a post contain the search term,
the status check would be overwritten by the OR clause . The solution I
made is a bit ugly so the syntax may need some change, asked for it on
gitter but no replies. Anyway, this is a temporary fix.

Fix for #791

---

anchor/routes/admin.php

Fixes an issue with image upload path returning `//content/` incorrectly instead of `/content/`.
As I noted [on the forum](http://forums.anchorcms.com/releases/0-10-testing/?page=1#post-6141) I'm not 100% if this is just an issue on my installation or not — if it is just me, just close this.

Fix path for image uploads

---

system/database/query.php
system/route.php

Fixed issues with [PR 789](https://github.com/anchorcms/anchor-cms/pull/789) that didn't follow the contributing guidelines.
"Anchor works wonderfully on HHVM v3.4.0 and sees a pretty great performance increase.
The only change required is that HHVM requires instanceof constructs be used with fully qualified class names instead of relative class names.
This is a non-breaking change and works for both the PHP and HHVM interpreters."

Added fully qualified namespacing

---

anchor/routes/posts.php

Sorry that I've had to create and close a couple of pull requests, I'm still learning.
Anyway, this has fixed #635 where the post date doesn't update automatically. It only updates when it has previously been a draft and is now published - presumably for the first time.

Update post date if published for the first time

---

anchor/routes/categories.php
anchor/routes/comments.php
anchor/routes/fields.php
anchor/routes/metadata.php
anchor/routes/pages.php
anchor/routes/pagetypes.php
anchor/routes/posts.php
anchor/routes/users.php
anchor/routes/variables.php
system/helpers.php

The fix that has been produced encodes quotation marks (both single and double) in fields that will be stored in the database. This protects the user of the admin panel from stored XSS attacks (by a potential other user).
To my base knowledge, this should now be able to close issues #871 and #876, both of which report XSS vulnerabilities (persistent/stored) in the admin panel when entering data into fields.
However, this fix does not prevent the DOM Based XSS that is still out there. Just be cautious when clicking links, or just don't click links that go to your admin panel...

Fixed to prevent the stored XSS vulnerability that has been found

---

anchor/routes/fields.php
anchor/routes/pages.php
anchor/routes/posts.php
anchor/views/pages/edit.php
anchor/views/posts/edit.php

#896 
Once again, excluded certain fields from being encoded, replica because old branch died.

replica of older bugfix where there was a large unreadability in the editor

---

install/views/database.php

So unicode_ci should be the default as anchor-cms is meant to be a cms for all languages.
See also [this excellent article](http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci) on Stackoverflow

The utf8_unicode_ci encoding sorts chars as expected

---

install/storage/anchor.sql

When creating a new page, there is an mysql error: menu_order has no default value. This fixes it and everything still works fine (creating pages, the menu ordering etc)

Fixing error on page creation

---

anchor/models/extend.php

in anchor/models/extend.php $value in <input> tag isn't escaped. so when $value contains double quotes, it ends up breaking the document markup.

escaped text printed in input in Extend::html()

---

anchor/functions/categories.php

once categories are read, categories is not rewound and hence returns false after iterating through once.

added rewind to categories()

---

anchor/libraries/template.php

If there exists a template named like the given custom page type, anchor will include it instead of the default page template.
With this, you can create for example a custom page type "gallery", for picture galleries, which need a unique template with the required markup and JS.

Pagetype templates

---

anchor/routes/pagetypes.php
anchor/views/extend/pagetypes/index.php

This pull request fix the issue https://github.com/anchorcms/anchor-cms/issues/939
I solved some problems when adding and updating a page type in the "extend" section:
- Display "All pages" pagetype at the beginning when there isn't another page added
- Empty field validation for all fields (adding and updating)
- Duplicates when create the same page
- Validation of primary key slug (key)
- Fix uncaught exception
@CraigChilds94. I hope this will help. If you need to change anything please let me know.
You can test the demo here:
http://visiopro.com.ve/site/anchor/admin
User: admin
Pass: 123456

Fixed "Uncaught Exception" when updating a page type

---

anchor/views/assets/css/admin.css

Margins need to be smaller to keep menu in one line with Polish
translations.
Additional CSS code require the pl-PL class in body.

Layout fix for translations: CSS code for pl-PL

---

anchor/migrations/212_insert_default_dashboard_meta_key.php
install/libraries/installer.php
install/routes.php
install/run.php
system/database/connectors/mysql.php

Attempt number 3 to commit to Anchor (#803, #1075)
- Anchor has an additional dependency on mbstring.
- Fixes the installation script failing if the database doesn't already
exist.
- Fixes the installation script failing if a full working database
already exists.
- Fixes a user being able to maliciously run the installation script to
overwrite a database.
- Fixes the URL not being escaped correctly when written into the PHP
script.
- The dirname() function on PHP for Windows can return strings
containing the \ character which will cause the installation to not
complete successfully if the user has not overridden it.
- Fix #1034.
- Fix #1035.

Fix Database Existence Crashes + Install Failures

---

install/routes.php

Add the line missing from the routes file (mentioned in issue) so the $vars exception is not thrown
- Added `$vars['messages'] = Notify::read();` to line 181 of the routes file
@protomorph Sorry, couldn't see your PR so created my own.

Remove undefined variable in routes file

---

install/storage/htaccess.distro

This change to the .htaccess file will allow anchor directories to be processed by the CMS as though the directories did not exist. However, if the user creates a directory "something" and also creates a page whose slug is "something" the directory will be prefered over the page. 
I'm currently using a htaccess file modified according to the changes here on my site, I tried running a clean install of the master branch but ran into the problem in #1034, however the htaccess file was created correctly. 
- Modified `install/storage/htaccess.distro` to allow pages with slugs equivalent to anchor directories to be correctly displayed.

Partial fix for #961

---

anchor/routes/site.php
install/libraries/installer.php

In an older version of Anchor, the Session was used to pass search terms between the function handling the post request and the function handling the get request to `search/all/(term)`. This, as of c60d201e1503e42bb67d82acbf5d59b5b79794e3 way back in 2013, was not used and simply not cleaned up. 
- Removed unused session changes
- Refactored ternary statement for allowing set values in `$whatSearch` to a switch statement.
---
While fixing the above, I realized that searching for anything that wasn't alphanumeric (and spaces) would fail as the url was encoded through `slug()` rather than `rawurlencode()`. I also discovered that the search function allowed the use of % and _ as wildcards.
Also, searching for an empty string returns all posts, I have left this functionality untouched though …

Fix for #1087 / Feature: Better search functionality

---

anchor/views/pages/edit.php

Attempt number 3 to commit to Anchor (#803, #1075)
- Fixed setting a page to be a child of Posts causes a crash ("Trying to
get property of non-object").

Prevent Posts Page Being A Parent

---

install/run.php

`DateTimeZone::listAbbreviations` returns an incorrect list of timezone offsets because of historical reasons. It can still be used, however, if the list is iterated over and each timezone is calculated based on the time the script was run. [Credit is due to Jonathan on SO](http://stackoverflow.com/questions/1727077/generating-a-drop-down-list-of-timezones-with-php/21211073#21211073)
- Refactored `timezones()` function to display correct offsets.

Fix for #1089 (Incorrect timezone for Dhaka)

---

anchor/routes/fields.php

If an image or file is uploaded as a custom field to a post, and the post is saved, it would produce an error as the script assumed that every value in `$input` was a string. 
- Use `array_walk_recursive` instead of foreach to run the values through `eq()`

Fix #1068 (fields edit bug)

---

anchor/libraries/validator.php
install/routes.php
install/views/account.php
install/views/complete.php
install/views/database.php
install/views/metadata.php
install/views/start.php

Simple fix, changing the catch statement to catch all `Exception`s rather than just `PDOException`s allowed all exceptions to be caught and the installer to be notified without an error page. 
- Fix validator bug where if the value was null, checks would always pass (ran into this while making the installer break) 
- Catch `Exception` rather than `PDOException` to avoid showing database info if the connection fails
- Add `Notify::Read` to all install views so that the user can be notified about what went wrong.

Fix #1096 (Database connection details visible...)

---

themes/default/article.php

`article_markdown` used to be used in themes instead of `article_html` to display the markdown, however, due to 8c3ef08d681b55da553b9f04a30085bd4a16d125, `article_markdown` no longer correctly displayed the HTML. Rather than reverting that change, which I believe is good as it makes the function return what it sounds like it should return, I changed the theme to use `article_html`. 
- Use `article_html` instead of `article_markdown` when displaying articles.

Fix: Articles should display html, not markdown

---

system/helpers.php

htmlspecialchars() now accept arrays
in system/helpers.php modify function e()
Allows htmlspecialchars() accept and process arrays

htmlspecialchars() now accept arrays

---

anchor/composer_check.php

Fixes and makes Anchor `composer install` as well as report any issues as required.
- Altered `composer_check.php` to have Anchor install dependencies.
Anchor now should attempt to `composer install`. Anchor will also report on any errors.

C'mon! Atleast try compose our dependencies!

---

anchor/functions/pages.php
themes/default/header.php

I added a function called page_description to select either post_description or site_description.
Made changes to the headers file in default theme so page_description is being used there. 
Plus enabled the function for selecting page_title in same file.

Fixing a better metadata view for the default theme

---

anchor/functions/pages.php
themes/default/header.php

I said that #1113 would improve metadata views but I mistakenly removed the main site description and set the wrong title. 
- Changed the default theme to use page_title for meta in og:title
- Made it so that page_description points to site description if no article is being viewed.
- Add a description field for pages so that metadata is further customizable and can be more relevant. (site_description for main page <- page_description for pages <- article_description for posts)

Mistakes were made in #1113. Metadata has correct info now.

---

anchor/routes/posts.php

When viewing posts with a particular status, the pagination wasn't working. The actual "status" part of the URL was being dropped. This fixes that.
For example:
- You're looking drafts, at: *admin/posts/status/draft*
- You click on page two in the pagination bar at the bottom.
- The link goes to: *admin/posts/status/2*
- It should have gone to: *admin/posts/status/draft/2*
This fix just adds the "status" text back into the URL.

fixing "status" pagination in admin post listing

---

anchor/models/extend.php

Added a missing line in order to fully populate image and file type extend fields in the post editor. Saved images and files are no longer wiped out by editing a post as described in #1150.
- Added line to `Extend::html()`

Fix issue #1150

---

system/start.php

Ran into an issue that's quite comparable to #1045. Basically it boils down to a missing anchor/config/session.php file which makes the Config::get('session') call return it's default value (null) after which the Session::setOptions() call fails because it requires an array as first argument.
There is still a failure-path hidden in here (if the session.php file exists but returns anything but an array) but I think that scenario is even less likely to happen then the one from #1045
Adding the default return value to the Config::get() call will 'fix' this

Proposed fix for #1045

---

anchor/config/aliases.php
anchor/run.php
index.php
install/config/aliases.php
install/index.php

Saw ticket #1180, did some checking, only failure was the Error alias (since PHP7 has it's own), fixed that.
Didn't look at the mcrypt stuff, will do at a later date probably.
- Renamed the Error alias to Errors
- Replaced dirname call with __DIR__

PHP7 compatibility

---

anchor/migrations/220_alter_meta_field
anchor/models/extend.php
install/storage/anchor.sql

This PR adds a much needed boolean custom field type (called a "toggle"), addressing #615. (More discussion on #703.)
Given that the `field()` function defines:
$field->value = Json::decode($meta ? $meta->data : '{}');
It made the most sense to follow convention and store the toggle value as JSON in the following format (`anchor_page_meta`):
+----+------+--------+--------------+
| id | page | extend | data         |
+----+------+--------+--------------+
| 17 |    2 |      4 | {"toggle":1} |
+----+------+--------+--------------+
The straightforward implementation yields a custom checkbox which themes can, of course, take advantage of to render content on the page differently depending on the state of the toggle:
<?php if(page_custom_field('toggle')) :?>
<p>Toggle is on</p>
<?php else: ?> …

Feature: Toggle Custom Field Type

---

anchor/helpers.php

Access to site page starting with `admin` slug was impossible.
This fixes the issue #1186, which made access to site page which slug started with `admin` was impossible.
- The `is_admin` helper was modified to allow access to pages with slug starting with `admin`.

Fix issue #1186

---

anchor/helpers.php
system/input.php

The cause of this bug was bc202b52e08cd48c5cea0508c83bd40fb588a645, as everything was encoded when first fetched, nearly every input was encoded twice, and the JS was encoded. The fix was to remove this, and also check everywhere `Input::get()` was used to ensure that encoding wasn't missed (nowhere...).
- Revert bc202b52e08cd48c5cea0508c83bd40fb588a645, which encoded all input
- Remove decoding of input when updating post as it is no longer needed.

Fix for #1046 (Custom JS is being escaped)

---

.gitignore
anchor/helpers.php
anchor/language/en_GB/global.php
anchor/libraries/update.php
anchor/routes/admin.php
anchor/views/upgrade.php
index.php

This feature aims to simplify the process that a user must follow to upgrade AnchorCMS. Now it is no longer download the archive, and FTP. All you need to do is click a button, and hope for the best!
- Added to `.gitignore`, so git doesn't see the upgrade data. Simply just temporary files.
- Added helper methods to delete file trees and recursively copy files.
- Added a few words and phrases to the `enGB` locale - all dealing with the upgrade functionality.
- Updated the function to get the latest version number.
- Added a new function that upgrades Anchor from inside Anchor (complete with debugging messages).
- Updated the `GET` route and added a `POST` route to better reflect the procedure of upgrading.
- Updated the front-end to look more effective.
Just placing this here for QA …

Self-Upgrading Feature

---

anchor/routes/pages.php

Missed page ID on add page route
- Changed `$id` to `$page->id` on add page route (L222)

Fixes #1208

---

themes/default/article.php

Comments are stored HTML encoded in the database, and then re-encoded before being sent to the client
Remove the HTML encoding from the default theme for comments.

Fix comments having HTML escaped characters

---

anchor/migrations/21_alter_comments_date.php
anchor/migrations/61_alter_posts_created.php

Specify `CURRENT_TIMESTAMP` as the default for `DATETIME` columns to avoid the `Invaild use of Null value` error.
- add `DEFAULT CURRENT_TIMESTAMP` to the migrations SQL statements of 21_alter_comments_date.php and 61_alter_posts_created.php.

Specify CURRENT_TIMESTAMP as the default for DATETIME columns. Fix #1219

---

anchor/.htaccess

I reported this to the MITRE corporation yesterday. The problem is not that stack traces are logged to `/anchor/errors.log`, but more that the `errors.log` file is accessible via the web with the default installation of Anchor CMS.
Normally the `errors.log` file wouldn't contain credentials. However, when you perform a denial of service on the website you have the chance that Anchor CMS will make too much concurrent connections to MySQL. This will throw a PHP error including the stack trace and arguments to `/anchor/errors.log`. The arguments contain the database credentials.
Therefore it is possible that the database credentials are accessible via the `error.log` on `http://an-anchor-blog[dot]com/anchor/errors.log`.
This fix will block all access to the Anchor directory since there's no …

Fixed CVE-2018-7251

---

anchor/.htaccess
anchor/views/assets/.htaccess
install/storage/htaccess.distro

It seems like my pull request #1248 broke access to the assets folder, as reported in issue #1249. The only access needed in the `/anchor` folder is for the assets, so I added a `.htaccess` file which allows all access to the assets folder. This seems like a clean fix to me.
To be sure everything works as it should I tested it just now on my local machine.
The `Allow from all` in the assets folder allows all access to admin assets from the web. My previous pull request blocked access to these files. Sorry for the inconvenience!
- Added a `.htaccess` file

Allow access to the admin asset folder

---

anchor/models/extend.php

Remove content path with empty image fields, only output path if the custom image field is populated.
- Conditionally output the field value if it's set.

Fix custom field file save with empty

---

anchor/views/assets/js/upload-fields.js

Make custom field file uploader behave as expected
- modify post-upload event handler to modify pre-populated hidden form field attribute rather than append a new one. Causes post/page save action to update database correctly.

Fix for #1239: Custom field uploader 'content' bug

---

composer.json

Corrects an error in the 'type' property that does not pass Composer's validators.
Changed uppercase `CMS` to lowercase `cms`.

Fix composer.json 'type' to match regex pattern

---

anchor/views/partials/header.php

I just noticed in the admin area the Header always says: "ManageMyBlog" instead of "Manage MyBlog"
- Just added a space on the header.php

added a spacebar between Manage and the sitename

---

anchor/routes/pages.php

My guess is originally it was planned to create a page object before saving, but it wasn't necessary. This clause only triggers when the title field is empty or doesn't meet some criteria.
Just pass a 0 value id because it's not required to have an one on pages that don't exist yet.

Fixes #1231, You don't need an id for a page that doesn't exist yet

---

anchor/libraries/notify.php

the notifications on the javascript side were not shown because the notifications element was not created if there was no message in the session.
- return a empty element notifications on notify::read

fixing notificantions not displayed error

---

.travis.yml
test/travis-ci/release.sh

This adds the `deploy` directive to the Travis configuration which *should* enable us to automatically build releases on tagged commits. Requires testing.  
This is up for debate, no merge immediately, please.

Added release automation for Travis-CI
