LICENSE
composer.json

Added LICENSE file and improved composer.json

Added LICENSE file and improved composer.json

---

anchor/libraries/anchor.php
anchor/libraries/migrations.php

Resubmitting #800 to 0.9-dev branch.

Fix that makes it possible to use down() function in migrations 

---

anchor/views/assets/css/admin.css
anchor/views/extend/metadata/edit.php

Always show the value of the posts_per_page slider in the admin interface.
Tested with a fresh installation.

Show value of the posts_per_page slider

---

anchor/routes/site.php

Someone probably made a typo and str_replaced '--' instead of '-'. Fix for issue #849

Fix for #849

---

anchor/functions/helpers.php

The functions were just sitting there. (l 95 and 99)
Tested on local server, works well.

Added body class for page and article

---

anchor/functions/articles.php
anchor/models/comment.php

Fixes feature/bug #863 and moved here because of a request in #864.

improved article pagination

---

anchor/libraries/update.php

Fixes #794

---

anchor/models/page.php
anchor/routes/site.php
themes/default/header.php

Creates feature #866 possible.
A new item in the POST to the search is needed, this needs to be called 'whatSearch' (it can be changed if desired).

Added feature where searching is available for pages and posts

---

anchor/libraries/update.php

Fixes issue #885.
I'm going to leave this branch open on my end, so that when a new fix is spotted, the title will be incremented, and the fix given a PR.
Cheers. :+1: :v:

General fixes #1: Result wasn't a variable when failed to update

---

anchor/functions/search.php
anchor/routes/site.php
themes/default/search.php

#888 
Something went wrong with the other branch. This is an exact replica.

replica of old multi-fix

---

anchor/functions/menus.php
anchor/functions/pages.php
anchor/views/pages/index.php

#887 
The exact same file changes, just something went wrong with the old branch.

replica of old child/parent bugfix

---

anchor/routes/pages.php
anchor/routes/posts.php
anchor/views/assets/css/admin.css
anchor/views/assets/js/autosave.js
anchor/views/assets/js/editor.js
anchor/views/assets/js/redirect.js
anchor/views/pages/add.php
anchor/views/pages/edit.php
anchor/views/posts/add.php
anchor/views/posts/edit.php

#884
Essentially, something went wrong, this is a reopening.

replica of old autosave feature

---

install/run.php

This fixes the issue #893 where the timezone during the installation was wrong.
I made this PR before and now I'm doing it again to respect the contributing.md of this project and to make it mergeable. Sorry for the mess, it'll not happen again.

Fixed wrong timezone during installation

---

app/storage/schema_mysql.sql

The installer complains about the lack of a mysql schema, this is an adaptation of the sqlite one.

Develop branch : Adding missing mysql schema

---

anchor/routes/admin.php

If user is logged in, they cannot reach the login page again

---

anchor/routes/variables.php

Throw an error when key empty and adjust max character

---

app/storage/schema_mysql.sql

Installer: fix and update MySQL schema

---

app/src/Controllers/Admin/Vars.php
app/src/Controllers/Installer/Install.php

This PR also fix admin URL after install

Variables form create

---

app/src/Url.php
app/views/posts/index.phtml

Multiple query strings prevented by removing actual query.
Plus little UI update on admin posts index page.

Url query multiplication fix

---

anchor/views/assets/css/forms.css

I resize the label size.
The reason: When you have other languages then english the labels look really creapie. So I changed the size a little bit.

Label Min-Width

---

anchor/views/comments/index.php

Statuses of comments were without translation.

Missing translations fixed.

---

anchor/routes/site.php

Fixed the error with the rss feed

---

anchor/views/error/404.php
install/views/error/404.php
system/error.php

I found some XSS Vulnerabilities, in the error Pages for 404 Errors, and a XSS in the "Uncaught Exception" Error Page. I fixed this Issue by using htmlspecialchars.

Filtered some XSS in Error-Pages

---

anchor/language/en_GB/panel.php
anchor/routes/admin.php
anchor/routes/panel.php
anchor/run.php
anchor/views/panel.php
anchor/views/partials/header.php

Welcome page / first page in admin panel

---

anchor/views/assets/js/editor.js

Now it will react only for key shortcut ctrl+s.

Bug fix for atl+s.

---

anchor/views/partials/header.php

The additional class in body for correcting bugs of layout in other
languages. It will add country code as class eg: en-GB, pl-PL.

Layout fix for translations: extra class in body

---

anchor/functions/articles.php
anchor/functions/pages.php

This helps fetch a custom field for posts/pages, within say, a while/foreach on another page - looping through content.

Pass ID in to custom field functions to fetch particular field

---

readme.md

Explained in issue #1025 
Added a label for the feature request in the readme.md

Add A Label for Feature Requests

---

.github/CONTRIBUTING.md

fixed typo

---

anchor/models/extend.php

Fix for bug with file loss in custom fields.
Added condition that prevents overwriting the field by empty data.

Fix for bug #1050

---

anchor/views/assets/css/admin.css
anchor/views/assets/js/dragdrop.js

Fixed the dragleave issue. I changed some css classes, to get it working.

Fix Drag'n'Drop

---

anchor/functions/config.php
anchor/language/en_GB/pages.php
anchor/libraries/anchor.php

Attempt number 3 to commit to Anchor (#803, #1075)
- Fix 2 typos.
- Explanation didn't help to explain.
- Grammar mistake fixed.

Fix Typos, Field Explanation & Grammar

---

install/libraries/installer.php

Just spotted a regression after #1077.

Fix security bug when attacker has valid database credentials

---

install/libraries/installer.php

Testing this evening revealed regression after #1081. PDO is definitely quirky!

Bug Fix : PDO quote didn't work like I expected it to

---

anchor/migrations/212_insert_default_dashboard_meta_key.php
install/routes.php

Rename the dashboard migration so class matches file name
- Rename the dashboard migration so class matches file name

1034 migration issue

---

anchor/models/post.php

Check if post exist and return false if not, to prevent exception and show 404 error
> Uncaught Exception
> 
> Trying to get property of non-object
> 
> Origin
> 
> anchor/models/post.php on line 20
> 
> Trace
> 
> #0 /home/konstantin/sites/unicore.dev/anchor/models/post.php(20): System\Error::native(8, 'Trying to get p...', '/home/konstanti...', 20, Array)
> #1 /home/konstantin/sites/unicore.dev/anchor/models/post.php(14): Post::getCommentCount(false)
> #2 /home/konstantin/sites/unicore.dev/anchor/routes/site.php(103): Post::slug('asdasd')
> #3 [internal function]: {closure}('asdasd')
> #4 /home/konstantin/sites/unicore.dev/system/route.php(152): call_user_func_array(Object(Closure), Array)
> #5 /home/konstantin/sites/unicore.dev/system/router.php(152): System\Route->run()
> #6 …

Check if post exist and return false if not, to prevent exception and show 404 error

---

.github/CONTRIBUTING.md
composer.json

Discussed about with @daviddarnes.
CC:
@rwarasaurus, @CraigChilds94, @idiot

Composer and Contributing updates

---

app/views/assets/less/forms.less

just stumbled across and it bugged me way too much

Fixed select elements in Webkit on MacOS

---

.github/CONTRIBUTING.md
anchor/config/aliases.php
anchor/functions/pages.php
anchor/migrations/220_alter_meta_field
anchor/models/extend.php
anchor/routes/pages.php
anchor/routes/posts.php
anchor/run.php
anchor/views/assets/js/editor.js
composer.json
index.php
install/config/aliases.php
install/index.php
install/libraries/installer.php
install/storage/anchor.sql
system/start.php
themes/default/header.php

Keep `pre-1.0-develop` up to date with all the bugfixes and what not.

Keeping things updated

---

anchor/models/extend.php

Add some character escaping to fix image uploading. NO idea if this is a good solution, just implementing the fix proposed by @mozzillation in #1174 
- Added some character escaping...?

Fix issue #1174

---

anchor/routes/admin.php

The returned path is not correct.
Add extra "/" to correct the path.

Fix path for uploaded images

---

anchor/views/categories/add.php
anchor/views/categories/edit.php

Uploading image/file in category not working with custom file fields
solved by adding upload-fields.js to edit.php and add.php in \anchor\views\categories

added upload-fields.js

---

install/index.php

Update install.php to reflect new minor version
- installed constant 'VERSION' is now 0.12.3

fix issue #1221

---

anchor/routes/admin.php

$uri parameter was missing rtrim function, resulting in //content address
- Adding rtrim function

Fixing image URL on file upload

---

anchor/routes/variables.php
composer.lock

This fixes a weird confusion with variables when updating a custom site variable.
- Fix the variables
- Improve readability
- Fix bug with validation which required you to change the name

Custom site variable saving fix. Issue #1259

---

.travis.yml

chore: cache dependencies

---

anchor/models/extend.php
anchor/views/assets/js/upload-fields.js

Uploading and saving images worked fine, but the code was not reflected to the process_file function. Fixed!
The File extension type was not saving the file for the post and page. This PR fixes this issue.
Also note: #1239 has been fixed AFAI can tell. Will determine by asking on the thread.
- Added the file saving functionality
- Tidied up various parts of the upload functionality (only for readability)

Fixed upload and savings of files.

---

install/run.php

When choosing the Anchor timezone, the user is presented with a list of time zones which are adjusted according to daylight savings time. This PR removes the DST offset and provides a more standardized timezone format similar to the Windows 10 UI.
Thanks to @nitwhiz for the help determining how best to present time zones to the user. See #1145 for the discussion.
- Adjusted the `timezones()` function to provide more user-friendly output.

Adjust time zones to handle DST

---

anchor/routes/posts.php
anchor/views/posts/add.php

When Auto-allow comments was checked it didn't actually allow comments automatically on new posts, this commit fixes this problem.

Fixed auto-allow comments

---

Dockerfile

Correctly modify variables_order in php.ini
